Algoritmo "POSITIVOOUNEGATIVO"
// Descrição   : Verificar se o número é positivo ou negativo
// Autor(a)    : Gabriel Fabbri
// Data atual  : 23/02/2024
Var
// Seção de Declarações das variáveis 
   n1, valorPositivo: real

Inicio

Escreval("Digite um numero: ")
Leia(n1)

valorPositivo <- 0

Se(n1 >= valorPositivo) entao
      Escreval("O Número", n1, " é positivo")
senao
     Escreval ("O número", n1, " é negativo")
Fimse


Fimalgoritmo